- name: copy /etc/modules
  copy:
    src: files/modules
    dest: /etc/modules
    mode: 644

- name: copy expand_rootfs.sh
  copy:
    src: files/expand_rootfs.sh
    dest: /tmp/expand_rootfs.sh
    mode: 700
  when: kickstart_resize_rootfs

- name: expand root filesystem
  shell: /tmp/expand_rootfs.sh
  ignore_errors: true
  when: kickstart_resize_rootfs

# FIXME (sorki): this fails with
# stderr: Re-reading the partition table failed.: Device or resource busy

- name: erase packages for minimal install
  apt: name={{ item }} state=absent purge=yes
  with_items:
  - desktop-base
  - lightdm
  - lx*
  - gnome*
  - x11*
  - xserver*
  - raspberrypi-artwork
  - wolfram-engine
  when: kickstart_minimal

- name: erase no longer required packages
  shell: apt-get -y autoremove
  when: kickstart_autoremove

- name: update fw via rpi-update
  shell: "UPDATE_SELF=0 SKIP_WARNING=1 rpi-update"
  when: kickstart_rpi_update

- name: dist upgrade
  apt: upgrade=dist
  when: kickstart_dist_upgrade

- name: set hostname
  hostname: name={{ new_hostname }}

- name: reboot
  #command: /sbin/shutdown -r now
  shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action:
    wait_for
      host={{ new_hostname }}
      port=22
      state=started
      delay=15
      timeout=300
      connect_timeout=15
  sudo: false

- name: resize2fs
  shell: resize2fs /dev/mmcblk0p2
  when: kickstart_resize_rootfs

- name: copy bashrc
  copy:
    src: files/bashrc
    dest: /root/.bashrc
    mode: 644
