#!/bin/bash

target="raspberrypi.lan"

if [ $# -gt 0 ]; then
    target=$1
    shift
fi

echo "Kickstarting ${target}"

ANSIBLE_CONFIG=kickstart_config ansible-playbook -v kickstart.yml \
  --extra-vars="target=${target}" $*
