---

- include: plays/common.yml
- include: plays/devel.yml
- include: plays/gps.yml
- include: plays/hostapd.yml
- include: plays/netconnectd.yml
- include: plays/ntpserver.yml
- include: plays/ros.yml
- include: plays/ws2812.yml
