---

# resize root partition to full size
kickstart_resize_rootfs: true

# erase packages for minimal install (no X11, wolfram)
# useful for cleaning official rpi images
kickstart_minimal: false

# erase no longer required packages (apt-get -y autoremove)
kickstart_autoremove: false

# update firmware via rpi-update
kickstart_rpi_update_firmware: false

# update kernel via rpi-update
kickstart_rpi_update_kernel: false

# perform dist upgrade
kickstart_dist_upgrade: false

# add user for deployment purposes
kickstart_add_deploy_user: true
kickstart_deploy_user: deploy
kickstart_deploy_group: deploy

# disable 8192cu wifi power management
kickstart_disable_8192cu_power_management: false
