- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - avahi-daemon
    - avahi-discover
    - libnss-mdns

- name: enable avahi-daemon
  service: name=avahi-daemon state=started enabled=yes
