- name: restart sshd
  service: name=sshd state=restarted

- name: update mail aliases
  command: /usr/bin/newaliases

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

