- set_fact:
    hostapd_patches_git_target: '{{hostapd_workdir}}/hostapd-rtl871xdrv.git'
    hostapd_install_dir: /usr/local/bin

- name: prepare workdir
  file: path='{{ hostapd_workdir }}' state=directory

- name: get hostapd
  shell: 'cd {{ hostapd_workdir }};{{ item}}'
  with_items:
    - 'wget -nc https://w1.fi/releases/{{ hostapd_version }}.tar.gz'
    - 'tar xzvf {{ hostapd_version }}.tar.gz'

- name: get patches
  git: repo={{ hostapd_patches_git_repo }}
    dest={{ hostapd_patches_git_target }}
  tags: build

- name: patch hostapd
  shell: 'cd {{ hostapd_workdir }}/{{ hostapd_version}};{{ item}}'
  with_items:
    - 'patch -Np1 < {{ hostapd_patches_git_target }}/rtlxdrv.patch'
    - 'cp {{ hostapd_patches_git_target }}/driver_rt* src/drivers/'
    - 'cp {{ hostapd_patches_git_target }}/.config hostapd/'
    - 'cd hostapd; make & make install'
  ignore_errors: true
  # FIXME (srk) ^^ needs better patch

- name: provide unit file
  template: src=hostapd.service.j2
    dest=/etc/systemd/system/hostapd.service
  notify: systemd
  tags: service
