if [[ $- != *i* ]] ; then
  # Shell is non-interactive.  Be done now!
  return
fi

# load system specific
if [ -f ~/.bash_local ]; then
  . ~/.bash_local
fi

# export LANG="en_US.utf-8"
# export LC_ALL="en_US.utf-8"

export EDITOR="vim"
export PATH=$PATH:$HOME/bin

# Use bash-completion, if available
if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi
