- name: set /boot/cmdline.txt
  template: src=boot-cmdline.txt.j2
    dest="{{ chroot }}/boot/cmdline.txt"

- name: set /boot/config.txt
  template: src=boot-config.txt.j2
    dest="{{ chroot }}/boot/config.txt"
  when: rpi_legacy_config_txt
